name: collection_diff
version: 2.0.3+3
homepage: https://github.com/SunnyApp/collection_diff
description: A dart library that compares collections and returns the differences as a set of operations.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  crypto: ^3.0.0
  collection: ^1.15.0
  logging: ^1.0.0
  uuid: ^3.0.1
  flutter_test: 
    sdk: flutter
  flutter: 
    sdk: flutter
dev_dependencies: 
  sunny_dart: ^0.8.0+7
