name: collection_diff
description: A dart library that compares collections and returns the differences as a set of operations.
version: 1.0.3
homepage: https://github.com/SunnyApp/collection_diff

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  collection: ^1.15.0
  logging: ^1.0.0
  uuid: ^3.0.1

dev_dependencies:
  sunny_dart: ^0.8.0+7
  coveralls: ^5.10.0

dependency_overrides:
  crypto: 3.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
