name: collection_diff
version: 1.0.3
homepage: https://github.com/SunnyApp/collection_diff
description: A dart library that compares collections and returns the differences as a set of operations.
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  collection: ^1.16.0
  logging: ^1.0.2
  uuid: ^3.0.6
  flutter_test: 
    sdk: flutter
  flutter: 
    sdk: flutter
dev_dependencies: 
  coveralls: '<5.7.0'
  sunny_dart: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/sunny_dart
flutter: null
