name: collection_diff
version: 2.0.3+6
homepage: https://github.com/SunnyApp/collection_diff
description: A dart library that compares collections and returns the differences as a set of operations.
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  crypto: ^3.0.2
  collection: ^1.16.0
  logging: ^1.0.2
  uuid: ^3.0.6
  flutter_test: 
    sdk: flutter
  flutter: 
    sdk: flutter
dev_dependencies: 
  dartxx: 
    path: /Users/ericm/sunny/trippi_plugins/dartxx
